### ISSUE TITLE
Simple Icons Angular Component

### ISSUE THREAD

**Issue by vicentecalfo** [fbernhart/fbernhart#1]
Hi, Florian
I am writing to let you know, that I really liked the Simple Icons and I will use it in a project, for that I developed an Angular component.
On the documentation page I created a link to your project's Github website.
Follow the links from Github and NPM:
. https://www.npmjs.com/package/@vicentecalfo/ngx-simple-icons
. https://github.com/vicentecalfo/ngx-simple-icons

Kind regards.
Vicente Calfo

**Comment by fbernhart** [comment]
@vicentecalfo Thanks a lot for linking back and congratulations on your project! 😊 

I'm not familiar with Angular myself, but maybe your project could be added to the [list of third party extensions ](https://github.com/simple-icons/simple-icons#third-party-extensions) of Simple Icons? Feel free to [open an issue](https://github.com/simple-icons/simple-icons/issues/new/choose) at Simple Icons and suggest it, if you want to.
